# Generated by Django 3.2.7 on 2021-10-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_articleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleImage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=100, verbose_name='İçerik'),
        ),
    ]
